image:  mcr.microsoft.com/dotnet/sdk:5.0

services: 
    - mcr.microsoft.com/mssql/server:2019-latest

stages:
    - test
    - build
    

job:
    stage: build
    tags: 
        - sopro
    script: 
        - cd AVATI
        - dotnet build

job2: 
    stage: test
    tags:
        - sopro
    script:
        - cd AVATI
        - cd UnitTests
        - dotnet test         
