version: "3.9"

services:
  db:
    image: zunaron/default_hub:finalDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"

  web:
    image: 7541f12cc8f4
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - "db"
   
 
 
  
 
    